by Anas: update p1 and p2 with corrected version

diff --git a/p1/Vagrantfile b/p1/Vagrantfile
--- a/p1/Vagrantfile
+++ b/p1/Vagrantfile
@@ -2,36 +2,48 @@ Vagrant.configure("2") do |config|
 
   # VM 1 - Server
   config.vm.define "abouzanbS" do |vm1|
-    vm1.vm.box = "ubuntu/jammy64"
+    vm1.vm.box = "debian/bookworm64"
     vm1.vm.hostname = "abouzanbS"
     vm1.vm.network "private_network", ip: "192.168.56.110"
     vm1.vm.provider "virtualbox" do |vb|
-      vb.gui = false  # Start without GUI to test
-      vb.memory = "512"
+      vb.gui = true
+      vb.memory = "1024"
       vb.cpus = 1
-      vb.name = "abouzanbS"
     end
     vm1.vm.provision "shell", inline: <<-SHELL
-      sudo apt update
-      echo "VM1 is ready"
+      echo "vagrant:vagrant" | sudo chpasswd
+      sudo apt update && sudo apt upgrade -y
+      sudo apt install -y  curl wget 
+
+
+      curl -sfL https://get.k3s.io | sh -
+      sleep 10
+      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/token.txt
     SHELL
   end
 
-  # VM 2 - ServerWorker  
   config.vm.define "abouzanbSW" do |vm2|
-    vm2.vm.box = "ubuntu/jammy64"
+    vm2.vm.box = "debian/bookworm64"
     vm2.vm.hostname = "abouzanbSW"
     vm2.vm.network "private_network", ip: "192.168.56.111"
     vm2.vm.provider "virtualbox" do |vb|
-      vb.gui = false  # Start without GUI to test
-      vb.memory = "512"
+      vb.gui = true
+      vb.memory = "1024"
       vb.cpus = 1
-      vb.name = "abouzanbSW"
     end
     vm2.vm.provision "shell", inline: <<-SHELL
-      sudo apt update
-      echo "VM2 is ready"
-    SHELL
+      sudo apt update && sudo apt upgrade -y
+      sudo apt install -y net-tools curl wget openssh-server
+      
+      
+      if [ -f /vagrant/token.txt ]; then
+        token=$(cat /vagrant/token.txt)
+        curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN="$token" sh -
+      else
+        echo "ERROR: Token file not found"
+        exit 1
+      fi
+    
+      SHELL
   end
-
 end
